[package]
name = "code-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
lsp-client = { path = "../lsp-client" }
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.91"
walkdir = "2.5.0"
